# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastLm <- function(y, X) {
    .Call(`_mmed_fastLm`, y, X)
}

fastLmSig <- function(y, X) {
    .Call(`_mmed_fastLmSig`, y, X)
}

fastLmSig_int <- function(y, X, inter) {
    .Call(`_mmed_fastLmSig_int`, y, X, inter)
}

calc_a_val <- function(gamma, sig2, tau2, psi = 0, G = 0) {
    .Call(`_mmed_calc_a_val`, gamma, sig2, tau2, psi, G)
}

calc_b_val <- function(a, gamma, sig2, tau2, y, G, Z, X, beta, ksi, psi = 0) {
    .Call(`_mmed_calc_b_val`, a, gamma, sig2, tau2, y, G, Z, X, beta, ksi, psi)
}

calc_expectation <- function(beta, gamma, psi, sig2, ksi, tau2, Y, G, Z, X, S, R, LLD, ULD, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_calc_expectation`, beta, gamma, psi, sig2, ksi, tau2, Y, G, Z, X, S, R, LLD, ULD, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

calc_beta_gamma_psi <- function(Y, Z, G, ES, ES2, interaction = TRUE) {
    .Call(`_mmed_calc_beta_gamma_psi`, Y, Z, G, ES, ES2, interaction)
}

calc_sig2 <- function(gamma, psi, interaction, beta, Y, G, Z, ES, ES2) {
    .Call(`_mmed_calc_sig2`, gamma, psi, interaction, beta, Y, G, Z, ES, ES2)
}

calc_ksi <- function(X, ES) {
    .Call(`_mmed_calc_ksi`, X, ES)
}

calc_tau2 <- function(ksi, X, ES, ES2) {
    .Call(`_mmed_calc_tau2`, ksi, X, ES, ES2)
}

oneMed_EM <- function(Y, G, S, R, lowerS, upperS, Z, X, interaction = TRUE, convLimit = 1e-4, iterationLimit = 1e4, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_oneMed_EM`, Y, G, S, R, lowerS, upperS, Z, X, interaction, convLimit, iterationLimit, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

calc_Q_matrix <- function(sig2, tau2, Z, X, G, ES, ES2, interaction = TRUE) {
    .Call(`_mmed_calc_Q_matrix`, sig2, tau2, Z, X, G, ES, ES2, interaction)
}

calc_V_mat <- function(gamma, psi, sig2, tau2, Y, G, beta, ksi, Z, X) {
    .Call(`_mmed_calc_V_mat`, gamma, psi, sig2, tau2, Y, G, beta, ksi, Z, X)
}

calc_U_mat <- function(gamma, psi, sig2, tau2, beta, ksi, Y, G, R, Z, X, LLD, ULD, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_calc_U_mat`, gamma, psi, sig2, tau2, beta, ksi, Y, G, R, Z, X, LLD, ULD, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

calc_OMEGA <- function(Y, G, S, R, lowerS, upperS, beta, gamma, psi, sig2, ksi, tau2, Z = 0L, X = 0L, interaction = TRUE, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_calc_OMEGA`, Y, G, S, R, lowerS, upperS, beta, gamma, psi, sig2, ksi, tau2, Z, X, interaction, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

deltaCI_one <- function(mu1, sig1, mu2, sig2, sig12, indL = 1, mu3 = 0L, sig3 = 0L, sig13 = 0L, sig23 = 0L, alpha = 0.05) {
    .Call(`_mmed_deltaCI_one`, mu1, sig1, mu2, sig2, sig12, indL, mu3, sig3, sig13, sig23, alpha)
}

bootstrapCI_one <- function(y, g, s, r, Z, X, lowers, uppers, delta, alpha, interaction = TRUE, indL = 1, bootStrapN = 1000L, convLimit = 1e-4, iterationLimit = 1e4, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_bootstrapCI_one`, y, g, s, r, Z, X, lowers, uppers, delta, alpha, interaction, indL, bootStrapN, convLimit, iterationLimit, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

mcCI_one <- function(mu, sig, delta, indL = 1, nIt = 10000, alpha = 0.05) {
    .Call(`_mmed_mcCI_one`, mu, sig, delta, indL, nIt, alpha)
}

mcp_calc_one <- function(mu, sig, delta, indL = 1, nIt = 10000, itPer = 1000) {
    .Call(`_mmed_mcp_calc_one`, mu, sig, delta, indL, nIt, itPer)
}

prodExPDF <- function(x, mu1_in, mu2_in, mu3_in, sig1_in, sig2_in, sig3_in, sig12_in, sig13_in, sig23_in, indL = 1, UPPERLIM = 30L, maxRet = 1e300L) {
    .Call(`_mmed_prodExPDF`, x, mu1_in, mu2_in, mu3_in, sig1_in, sig2_in, sig3_in, sig12_in, sig13_in, sig23_in, indL, UPPERLIM, maxRet)
}

exFindLower <- function(mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, indL = 1, pdfTol = 1e-5) {
    .Call(`_mmed_exFindLower`, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, indL, pdfTol)
}

exFindUpper <- function(mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, indL = 1, pdfTol = 1e-5) {
    .Call(`_mmed_exFindUpper`, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, indL, pdfTol)
}

exProdCDF <- function(x, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, maxRet = 1e300L, indL = 1) {
    .Call(`_mmed_exProdCDF`, x, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, maxRet, indL)
}

exProdCI <- function(alpha, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, maxRet = 1e300L, indL = 1, citol = 1e-8L) {
    .Call(`_mmed_exProdCI`, alpha, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, maxRet, indL, citol)
}

mySign <- function(x) {
    .Call(`_mmed_mySign`, x)
}

prodPDF_c <- function(x, z, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, indL = 1) {
    .Call(`_mmed_prodPDF_c`, x, z, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, indL)
}

findLower <- function(z, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, indL = 1) {
    .Call(`_mmed_findLower`, z, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, indL)
}

findUpper <- function(z, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, indL = 1) {
    .Call(`_mmed_findUpper`, z, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, indL)
}

prodCDF <- function(z, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, indL = 1) {
    .Call(`_mmed_prodCDF`, z, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, indL)
}

prodCI <- function(alpha, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, maxRet = 1e300L, indL = 1, citol = 1e-8L) {
    .Call(`_mmed_prodCI`, alpha, mu1, mu2, mu3, sig1, sig2, sig3, sig12, sig13, sig23, maxRet, indL, citol)
}

calc_a1_val_twoseq <- function(gamma_tilde, psi_tilde, h1, h2, sig2, gamma_1, psi_1, tau2_2, tau2_1, S2, G) {
    .Call(`_mmed_calc_a1_val_twoseq`, gamma_tilde, psi_tilde, h1, h2, sig2, gamma_1, psi_1, tau2_2, tau2_1, S2, G)
}

calc_b1_val_twoseq <- function(gamma_1, psi_1, gamma_tilde, psi_tilde, gamma_2, psi_2, h1, h2, sig2, tau2_1, tau2_2, beta, ksi_1, ksi_2, y, Z, G, X1, X2, S2) {
    .Call(`_mmed_calc_b1_val_twoseq`, gamma_1, psi_1, gamma_tilde, psi_tilde, gamma_2, psi_2, h1, h2, sig2, tau2_1, tau2_2, beta, ksi_1, ksi_2, y, Z, G, X1, X2, S2)
}

calc_a2_val_twoseq <- function(gamma_2, psi_2, h1, h2, S1, G, sig2, tau2_2) {
    .Call(`_mmed_calc_a2_val_twoseq`, gamma_2, psi_2, h1, h2, S1, G, sig2, tau2_2)
}

calc_b2_val_twoseq <- function(gamma_2, psi_2, h1, h2, gamma_tilde, psi_tilde, beta, gamma_1, psi_1, ksi_2, sig2, tau2_2, y, G, Z, X2, S1) {
    .Call(`_mmed_calc_b2_val_twoseq`, gamma_2, psi_2, h1, h2, gamma_tilde, psi_tilde, beta, gamma_1, psi_1, ksi_2, sig2, tau2_2, y, G, Z, X2, S1)
}

calc_c1_val_twoseq <- function(gamma_1, psi_1, gamma_2, psi_2, gamma_tilde, psi_tilde, tau2_1, tau2_2, sig2, G) {
    .Call(`_mmed_calc_c1_val_twoseq`, gamma_1, psi_1, gamma_2, psi_2, gamma_tilde, psi_tilde, tau2_1, tau2_2, sig2, G)
}

calc_d1_val_twoseq <- function(gamma_1, psi_1, gamma_2, psi_2, gamma_tilde, psi_tilde, rho, tau2_1, tau2_2, sig2, y, G, Z, X1, X2, beta, ksi_1, ksi_2, c1, c2) {
    .Call(`_mmed_calc_d1_val_twoseq`, gamma_1, psi_1, gamma_2, psi_2, gamma_tilde, psi_tilde, rho, tau2_1, tau2_2, sig2, y, G, Z, X1, X2, beta, ksi_1, ksi_2, c1, c2)
}

calc_c2_val_twoseq <- function(gamma_1, psi_1, gamma_2, psi_2, gamma_tilde, psi_tilde, tau2_1, tau2_2, sig2, G) {
    .Call(`_mmed_calc_c2_val_twoseq`, gamma_1, psi_1, gamma_2, psi_2, gamma_tilde, psi_tilde, tau2_1, tau2_2, sig2, G)
}

calc_d2_val_twoseq <- function(gamma_1, psi_1, gamma_2, psi_2, gamma_tilde, psi_tilde, rho, tau2_1, tau2_2, sig2, y, G, Z, X1, X2, beta, ksi_1, ksi_2, c1, c2) {
    .Call(`_mmed_calc_d2_val_twoseq`, gamma_1, psi_1, gamma_2, psi_2, gamma_tilde, psi_tilde, rho, tau2_1, tau2_2, sig2, y, G, Z, X1, X2, beta, ksi_1, ksi_2, c1, c2)
}

calc_corr_b_twoseq <- function(gamma_1, psi_1, gamma_2, psi_2, gamma_tilde, psi_tilde, tau2_2, sig2, G, c1, c2) {
    .Call(`_mmed_calc_corr_b_twoseq`, gamma_1, psi_1, gamma_2, psi_2, gamma_tilde, psi_tilde, tau2_2, sig2, G, c1, c2)
}

calc_corr_rho_twoseq <- function(b) {
    .Call(`_mmed_calc_corr_rho_twoseq`, b)
}

bothMissInt_ord <- function(Y, beta, Z, G, sig2, gamma_1, psi_1, gamma_tilde, psi_tilde, gamma_2, psi_2, h1, h2, ksi_1, ksi_2, X1, X2, tau2_1, tau2_2, ps1, ps2, lowS1, lowS2, highS1, highS2, nDivisions = 5L) {
    .Call(`_mmed_bothMissInt_ord`, Y, beta, Z, G, sig2, gamma_1, psi_1, gamma_tilde, psi_tilde, gamma_2, psi_2, h1, h2, ksi_1, ksi_2, X1, X2, tau2_1, tau2_2, ps1, ps2, lowS1, lowS2, highS1, highS2, nDivisions)
}

bothMissInt_ord_limits <- function(Y, beta, Z, G, sig2, gamma_1, psi_1, gamma_tilde, psi_tilde, gamma_2, psi_2, h1, h2, ksi_1, ksi_2, X1, X2, tau2_1, tau2_2, lowS1, lowS2, highS1, highS2, missKey1 = 0L, missKey2 = 0L, limit = 1e-14, stepCorrect = 1000.0) {
    .Call(`_mmed_bothMissInt_ord_limits`, Y, beta, Z, G, sig2, gamma_1, psi_1, gamma_tilde, psi_tilde, gamma_2, psi_2, h1, h2, ksi_1, ksi_2, X1, X2, tau2_1, tau2_2, lowS1, lowS2, highS1, highS2, missKey1, missKey2, limit, stepCorrect)
}

calc_expectation_twoseq <- function(gamma_1, psi_1, gamma_2, psi_2, gamma_tilde, psi_tilde, h1, h2, sig2, tau2_1, tau2_2, Y, Z, X1, X2, G, beta, ksi_1, ksi_2, S1, R1, S2, R2, LLD1, ULD1, LLD2, ULD2, nDivisions = 5L, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_calc_expectation_twoseq`, gamma_1, psi_1, gamma_2, psi_2, gamma_tilde, psi_tilde, h1, h2, sig2, tau2_1, tau2_2, Y, Z, X1, X2, G, beta, ksi_1, ksi_2, S1, R1, S2, R2, LLD1, ULD1, LLD2, ULD2, nDivisions, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

calc_beta_tilde_gamma2_twoseq <- function(Y, Z, G, ES1, ES1_2, ES2, ES2_2, ES1ES2, ES12ES2, ES1ES22, ES12ES22, int_gs1_Y = TRUE, int_gs2 = TRUE, int_s1s2 = FALSE, int_gs1s2 = FALSE) {
    .Call(`_mmed_calc_beta_tilde_gamma2_twoseq`, Y, Z, G, ES1, ES1_2, ES2, ES2_2, ES1ES2, ES12ES2, ES1ES22, ES12ES22, int_gs1_Y, int_gs2, int_s1s2, int_gs1s2)
}

calc_sig2_twoseq <- function(gamma_tilde, psi_tilde, gamma_2, psi_2, h1, h2, int_gs1_Y, int_gs2, int_s1s2, int_gs1s2, Y, beta, G, Z, ES1, ES1_2, ES2, ES2_2, ES1ES2, ES12ES2, ES1ES22, ES12ES22) {
    .Call(`_mmed_calc_sig2_twoseq`, gamma_tilde, psi_tilde, gamma_2, psi_2, h1, h2, int_gs1_Y, int_gs2, int_s1s2, int_gs1s2, Y, beta, G, Z, ES1, ES1_2, ES2, ES2_2, ES1ES2, ES12ES2, ES1ES22, ES12ES22)
}

calc_ksi2_gamma1_twoseq <- function(X2, G, ES1, ES1_2, ES2, ES1ES2, ES12ES2, gs1 = TRUE) {
    .Call(`_mmed_calc_ksi2_gamma1_twoseq`, X2, G, ES1, ES1_2, ES2, ES1ES2, ES12ES2, gs1)
}

calc_ksi1_twoseq <- function(X1, ES1) {
    .Call(`_mmed_calc_ksi1_twoseq`, X1, ES1)
}

calc_tau2_twoseq <- function(ksi_2, X2, G, gamma_1, psi_1, int_gs1, ES1, ES1_2, ES2, ES2_2, ES1ES2) {
    .Call(`_mmed_calc_tau2_twoseq`, ksi_2, X2, G, gamma_1, psi_1, int_gs1, ES1, ES1_2, ES2, ES2_2, ES1ES2)
}

calc_tau1_twoseq <- function(ksi_1, X1, ES1, ES1_2) {
    .Call(`_mmed_calc_tau1_twoseq`, ksi_1, X1, ES1, ES1_2)
}

twoSeqMed_EM <- function(Y, G, S1, R1, S2, R2, Z, X1, X2, lowerS1, upperS1, lowerS2, upperS2, int_gs1 = TRUE, int_gs1_Y = TRUE, int_gs2 = TRUE, int_s1s2 = FALSE, int_gs1s2 = FALSE, convLimit = 1e-4, iterationLimit = 1e4, nDivisions = 5L, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_twoSeqMed_EM`, Y, G, S1, R1, S2, R2, Z, X1, X2, lowerS1, upperS1, lowerS2, upperS2, int_gs1, int_gs1_Y, int_gs2, int_s1s2, int_gs1s2, convLimit, iterationLimit, nDivisions, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

calc_Q_matrix_twoseq <- function(sig2, tau2_1, tau2_2, Z, X1, X2, G, ES1, ES1_2, ES2, ES2_2, ES1S2, ES12S2, ES1S22, ES12S22, int_gs1 = TRUE, int_gs1_Y = TRUE, int_gs2 = TRUE, int_s1s2 = FALSE, int_gs1s2 = FALSE) {
    .Call(`_mmed_calc_Q_matrix_twoseq`, sig2, tau2_1, tau2_2, Z, X1, X2, G, ES1, ES1_2, ES2, ES2_2, ES1S2, ES12S2, ES1S22, ES12S22, int_gs1, int_gs1_Y, int_gs2, int_s1s2, int_gs1s2)
}

calc_V_mat_twoseq_S1 <- function(gamma_tilde, psi_tilde, gamma_2, psi_2, gamma_1, psi_1, h1, h2, sig2, tau2_1, tau2_2, Y, G, S_obs, beta, ksi_1, ksi_2, Z, X1, X2) {
    .Call(`_mmed_calc_V_mat_twoseq_S1`, gamma_tilde, psi_tilde, gamma_2, psi_2, gamma_1, psi_1, h1, h2, sig2, tau2_1, tau2_2, Y, G, S_obs, beta, ksi_1, ksi_2, Z, X1, X2)
}

calc_V_mat_twoseq_S2 <- function(gamma_tilde, psi_tilde, gamma_2, psi_2, gamma_1, psi_1, h1, h2, sig2, tau2_1, tau2_2, Y, G, S_obs, beta, ksi_1, ksi_2, Z, X1, X2) {
    .Call(`_mmed_calc_V_mat_twoseq_S2`, gamma_tilde, psi_tilde, gamma_2, psi_2, gamma_1, psi_1, h1, h2, sig2, tau2_1, tau2_2, Y, G, S_obs, beta, ksi_1, ksi_2, Z, X1, X2)
}

calc_V_mat_twoseq_S1S2 <- function(gamma_tilde, psi_tilde, gamma_2, psi_2, gamma_1, psi_1, h1, h2, sig2, tau2_1, tau2_2, Y, G, beta, ksi_1, ksi_2, Z, X1, X2) {
    .Call(`_mmed_calc_V_mat_twoseq_S1S2`, gamma_tilde, psi_tilde, gamma_2, psi_2, gamma_1, psi_1, h1, h2, sig2, tau2_1, tau2_2, Y, G, beta, ksi_1, ksi_2, Z, X1, X2)
}

calc_U_mat_twoseq_S1miss <- function(gamma_tilde, psi_tilde, gamma_2, psi_2, gamma_1, psi_1, h1, h2, sig2, tau2_1, tau2_2, Y, G, S_obs, R, beta, ksi_1, ksi_2, Z, X1, X2, LLD, ULD, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_calc_U_mat_twoseq_S1miss`, gamma_tilde, psi_tilde, gamma_2, psi_2, gamma_1, psi_1, h1, h2, sig2, tau2_1, tau2_2, Y, G, S_obs, R, beta, ksi_1, ksi_2, Z, X1, X2, LLD, ULD, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

calc_U_mat_twoseq_S2miss <- function(gamma_tilde, psi_tilde, gamma_2, psi_2, gamma_1, psi_1, h1, h2, sig2, tau2_1, tau2_2, Y, G, S_obs, R, beta, ksi_1, ksi_2, Z, X2, LLD, ULD, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_calc_U_mat_twoseq_S2miss`, gamma_tilde, psi_tilde, gamma_2, psi_2, gamma_1, psi_1, h1, h2, sig2, tau2_1, tau2_2, Y, G, S_obs, R, beta, ksi_1, ksi_2, Z, X2, LLD, ULD, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

calc_U_mat_twoseq_twomiss <- function(gamma_tilde, psi_tilde, gamma_2, psi_2, gamma_1, psi_1, h1, h2, sig2, tau2_1, tau2_2, Y, G, R1, R2, beta, ksi_1, ksi_2, Z, X1, X2, LLD1, ULD1, LLD2, ULD2, nDivisions = 5L, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_calc_U_mat_twoseq_twomiss`, gamma_tilde, psi_tilde, gamma_2, psi_2, gamma_1, psi_1, h1, h2, sig2, tau2_1, tau2_2, Y, G, R1, R2, beta, ksi_1, ksi_2, Z, X1, X2, LLD1, ULD1, LLD2, ULD2, nDivisions, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

calc_OMEGA_twoseq <- function(Y, G, S1, R1, S2, R2, Z, X1, X2, lowerS1, upperS1, lowerS2, upperS2, beta, gamma_tilde, psi_tilde, gamma_1, psi_1, gamma_2, psi_2, h1, h2, sig2, tau2_1, tau2_2, ksi_1, ksi_2, int_gs1 = TRUE, int_gs1_Y = TRUE, int_gs2 = TRUE, int_s1s2 = FALSE, int_gs1s2 = FALSE, nDivisions = 5L, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_calc_OMEGA_twoseq`, Y, G, S1, R1, S2, R2, Z, X1, X2, lowerS1, upperS1, lowerS2, upperS2, beta, gamma_tilde, psi_tilde, gamma_1, psi_1, gamma_2, psi_2, h1, h2, sig2, tau2_1, tau2_2, ksi_1, ksi_2, int_gs1, int_gs1_Y, int_gs2, int_s1s2, int_gs1s2, nDivisions, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

deltaCI_twoseq <- function(mu1, sig1, mu2, sig2, mu2b, sig2b, mu3, sig3, mu3b, sig3b, sig12, sig12b, sig13, sig13b, sig22b, sig23, sig23b, sig2b3, sig2b3b, sig33b, indL = 1L, alpha = 0.05) {
    .Call(`_mmed_deltaCI_twoseq`, mu1, sig1, mu2, sig2, mu2b, sig2b, mu3, sig3, mu3b, sig3b, sig12, sig12b, sig13, sig13b, sig22b, sig23, sig23b, sig2b3, sig2b3b, sig33b, indL, alpha)
}

bootstrapCI_twoseq <- function(y, g, s1, r1, s2, r2, Z, X1, X2, lowerS1, upperS1, lowerS2, upperS2, delta, alpha, int_gs1 = TRUE, int_gs1_Y = TRUE, int_gs2 = TRUE, int_s1s2 = FALSE, int_gs1s2 = FALSE, indL = 1, bootStrapN = 1000L, convLimit = 1e-4, iterationLimit = 1e4, nDivisions = 5L, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_bootstrapCI_twoseq`, y, g, s1, r1, s2, r2, Z, X1, X2, lowerS1, upperS1, lowerS2, upperS2, delta, alpha, int_gs1, int_gs1_Y, int_gs2, int_s1s2, int_gs1s2, indL, bootStrapN, convLimit, iterationLimit, nDivisions, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

mcCI_twoseq <- function(mu, sig, delta, indL = 1.0, nIt = 10000, alpha = 0.05) {
    .Call(`_mmed_mcCI_twoseq`, mu, sig, delta, indL, nIt, alpha)
}

calc_a_val_twosim <- function(gamma, psi, G, S_obs, h1, h2, sig2, tau2, rho) {
    .Call(`_mmed_calc_a_val_twosim`, gamma, psi, G, S_obs, h1, h2, sig2, tau2, rho)
}

calc_b_val_twosim <- function(gamma_same, gamma_diff, psi_same, psi_diff, h1, h2, rho, tau2_same, tau2_diff, sig2, Y, G, Z, beta, S_obs, X, ksi_same, ksi_diff) {
    .Call(`_mmed_calc_b_val_twosim`, gamma_same, gamma_diff, psi_same, psi_diff, h1, h2, rho, tau2_same, tau2_diff, sig2, Y, G, Z, beta, S_obs, X, ksi_same, ksi_diff)
}

calc_c_val_twosim <- function(gamma_same, gamma_diff, psi_same, psi_diff, G, tau2_same, tau2_diff, sig2, rho) {
    .Call(`_mmed_calc_c_val_twosim`, gamma_same, gamma_diff, psi_same, psi_diff, G, tau2_same, tau2_diff, sig2, rho)
}

calc_d_val_twosim <- function(gamma_same, gamma_diff, psi_same, psi_diff, rho, r, tau2_same, tau2_diff, sig2, Y, G, Z, X, beta, ksi_same, ksi_diff, c_same, c_diff) {
    .Call(`_mmed_calc_d_val_twosim`, gamma_same, gamma_diff, psi_same, psi_diff, rho, r, tau2_same, tau2_diff, sig2, Y, G, Z, X, beta, ksi_same, ksi_diff, c_same, c_diff)
}

calc_corr_b_twosim <- function(gamma_1, gamma_2, psi_1, psi_2, G, tau2_1, tau2_2, c1, c2, sig2, rho) {
    .Call(`_mmed_calc_corr_b_twosim`, gamma_1, gamma_2, psi_1, psi_2, G, tau2_1, tau2_2, c1, c2, sig2, rho)
}

calc_corr_r_twosim <- function(b) {
    .Call(`_mmed_calc_corr_r_twosim`, b)
}

bothMissInt_unord <- function(Y, beta, Z, G, sig2, gamma_1, psi_1, gamma_2, psi_2, h1, h2, ksi_1, ksi_2, X, tau2_1, tau2_2, rho, ps1, ps2, lowS1, lowS2, highS1, highS2, nDivisions = 5L) {
    .Call(`_mmed_bothMissInt_unord`, Y, beta, Z, G, sig2, gamma_1, psi_1, gamma_2, psi_2, h1, h2, ksi_1, ksi_2, X, tau2_1, tau2_2, rho, ps1, ps2, lowS1, lowS2, highS1, highS2, nDivisions)
}

bothMissPDF_unord <- function(x, Y, beta, Z, G, sig2, gamma_1, psi_1, gamma_2, psi_2, h1, h2, ksi_1, ksi_2, X, tau2_1, tau2_2, rho, ps1, ps2) {
    .Call(`_mmed_bothMissPDF_unord`, x, Y, beta, Z, G, sig2, gamma_1, psi_1, gamma_2, psi_2, h1, h2, ksi_1, ksi_2, X, tau2_1, tau2_2, rho, ps1, ps2)
}

bothMissInt_unord_limits <- function(Y, beta, Z, G, sig2, gamma_1, psi_1, gamma_2, psi_2, h1, h2, ksi_1, ksi_2, X, tau2_1, tau2_2, rho, lowS1, lowS2, highS1, highS2, missKey1 = 0L, missKey2 = 0L, nSteps = 1e4L, limit = 1e-14, stepCorrect = 1000.0) {
    .Call(`_mmed_bothMissInt_unord_limits`, Y, beta, Z, G, sig2, gamma_1, psi_1, gamma_2, psi_2, h1, h2, ksi_1, ksi_2, X, tau2_1, tau2_2, rho, lowS1, lowS2, highS1, highS2, missKey1, missKey2, nSteps, limit, stepCorrect)
}

bothMissInt_unord2 <- function(Y, beta, Z, G, sig2, gamma_1, psi_1, gamma_2, psi_2, h1, h2, ksi_1, ksi_2, ksi_3, X, tau2_1, tau2_2, tau2_3, rho, ps1, ps2, lowS1, lowS2, highS1, highS2, missKey1 = 0L, missKey2 = 0L) {
    .Call(`_mmed_bothMissInt_unord2`, Y, beta, Z, G, sig2, gamma_1, psi_1, gamma_2, psi_2, h1, h2, ksi_1, ksi_2, ksi_3, X, tau2_1, tau2_2, tau2_3, rho, ps1, ps2, lowS1, lowS2, highS1, highS2, missKey1, missKey2)
}

calc_expectation_twosim <- function(gamma_1, gamma_2, psi_1, psi_2, h1, h2, rho, sig2, tau2_1, tau2_2, Y, Z, X, G, beta, ksi_1, ksi_2, S1, R1, S2, R2, LLD1, ULD1, LLD2, ULD2, nDivisions = 5L, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_calc_expectation_twosim`, gamma_1, gamma_2, psi_1, psi_2, h1, h2, rho, sig2, tau2_1, tau2_2, Y, Z, X, G, beta, ksi_1, ksi_2, S1, R1, S2, R2, LLD1, ULD1, LLD2, ULD2, nDivisions, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

calc_beta_gamma_inter_twosim <- function(Y, Z, G, ES1, ES1_2, ES2, ES2_2, ES1ES2, ES12ES2, ES1ES22, ES12ES22, int_gs1 = TRUE, int_gs2 = TRUE, int_s1s2 = FALSE, int_gs1s2 = FALSE) {
    .Call(`_mmed_calc_beta_gamma_inter_twosim`, Y, Z, G, ES1, ES1_2, ES2, ES2_2, ES1ES2, ES12ES2, ES1ES22, ES12ES22, int_gs1, int_gs2, int_s1s2, int_gs1s2)
}

calc_sig2_twosim <- function(gamma_1, gamma_2, psi_1, psi_2, h1, h2, int_gs1, int_gs2, int_s1s2, int_gs1s2, Y, beta, Z, G, ES1, ES1_2, ES2, ES2_2, ES1ES2, ES12ES2, ES1ES22, ES12ES22) {
    .Call(`_mmed_calc_sig2_twosim`, gamma_1, gamma_2, psi_1, psi_2, h1, h2, int_gs1, int_gs2, int_s1s2, int_gs1s2, Y, beta, Z, G, ES1, ES1_2, ES2, ES2_2, ES1ES2, ES12ES2, ES1ES22, ES12ES22)
}

calc_ksi_twosim <- function(X, ES) {
    .Call(`_mmed_calc_ksi_twosim`, X, ES)
}

calc_tau2_twosim <- function(ksi, X, ES, ES2) {
    .Call(`_mmed_calc_tau2_twosim`, ksi, X, ES, ES2)
}

calc_rho_twosim <- function(ksi_1, ksi_2, X, tau2_1, tau2_2, ES1, ES2, ES1ES2) {
    .Call(`_mmed_calc_rho_twosim`, ksi_1, ksi_2, X, tau2_1, tau2_2, ES1, ES2, ES1ES2)
}

rhoInit <- function(y1, y2, X) {
    .Call(`_mmed_rhoInit`, y1, y2, X)
}

twoSimMed_EM <- function(Y, G, S1, R1, S2, R2, Z, X, lowerS1, upperS1, lowerS2, upperS2, int_gs1 = TRUE, int_gs2 = TRUE, int_s1s2 = FALSE, int_gs1s2 = FALSE, convLimit = 1e-4, iterationLimit = 1e4, nDivisions = 5L, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_twoSimMed_EM`, Y, G, S1, R1, S2, R2, Z, X, lowerS1, upperS1, lowerS2, upperS2, int_gs1, int_gs2, int_s1s2, int_gs1s2, convLimit, iterationLimit, nDivisions, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

calc_Q_matrix_twosim <- function(sig2, tau2_1, tau2_2, rho, Z, X, G, ES1, ES1_2, ES2, ES2_2, ES1S2, ES12S2, ES1S22, ES12S22, int_gs1 = TRUE, int_gs2 = TRUE, int_s1s2 = FALSE, int_gs1s2 = FALSE) {
    .Call(`_mmed_calc_Q_matrix_twosim`, sig2, tau2_1, tau2_2, rho, Z, X, G, ES1, ES1_2, ES2, ES2_2, ES1S2, ES12S2, ES1S22, ES12S22, int_gs1, int_gs2, int_s1s2, int_gs1s2)
}

calc_V_mat_twosim_S1 <- function(gamma_1, gamma_2, psi_1, psi_2, h1, h2, sig2, tau2_1, tau2_2, rho, Y, S_obs, G, beta, ksi_1, ksi_2, Z, X) {
    .Call(`_mmed_calc_V_mat_twosim_S1`, gamma_1, gamma_2, psi_1, psi_2, h1, h2, sig2, tau2_1, tau2_2, rho, Y, S_obs, G, beta, ksi_1, ksi_2, Z, X)
}

calc_V_mat_twosim_S2 <- function(gamma_1, gamma_2, psi_1, psi_2, h1, h2, sig2, tau2_1, tau2_2, rho, Y, S_obs, G, beta, ksi_1, ksi_2, Z, X) {
    .Call(`_mmed_calc_V_mat_twosim_S2`, gamma_1, gamma_2, psi_1, psi_2, h1, h2, sig2, tau2_1, tau2_2, rho, Y, S_obs, G, beta, ksi_1, ksi_2, Z, X)
}

calc_V_mat_twosim_S1S2 <- function(gamma_1, gamma_2, psi_1, psi_2, h1, h2, sig2, tau2_1, tau2_2, rho, Y, G, beta, ksi_1, ksi_2, Z, X) {
    .Call(`_mmed_calc_V_mat_twosim_S1S2`, gamma_1, gamma_2, psi_1, psi_2, h1, h2, sig2, tau2_1, tau2_2, rho, Y, G, beta, ksi_1, ksi_2, Z, X)
}

calc_U_mat_twosim_onemiss <- function(gamma_same, gamma_diff, psi_same, psi_diff, h1, h2, rho, tau2_same, tau2_diff, sig2, Y, G, Z, X, S_obs, R, beta, ksi_same, ksi_diff, LLD, ULD, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_calc_U_mat_twosim_onemiss`, gamma_same, gamma_diff, psi_same, psi_diff, h1, h2, rho, tau2_same, tau2_diff, sig2, Y, G, Z, X, S_obs, R, beta, ksi_same, ksi_diff, LLD, ULD, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

calc_U_mat_twosim_twomiss <- function(gamma_1, gamma_2, psi_1, psi_2, h1, h2, rho, tau2_1, tau2_2, sig2, Y, G, Z, X, R1, R2, beta, ksi_1, ksi_2, LLD1, ULD1, LLD2, ULD2, nDivisions = 5L, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_calc_U_mat_twosim_twomiss`, gamma_1, gamma_2, psi_1, psi_2, h1, h2, rho, tau2_1, tau2_2, sig2, Y, G, Z, X, R1, R2, beta, ksi_1, ksi_2, LLD1, ULD1, LLD2, ULD2, nDivisions, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

calc_OMEGA_twosim <- function(Y, G, S1, R1, S2, R2, lowerS1, upperS1, lowerS2, upperS2, beta, gamma_1, gamma_2, psi_1, psi_2, h1, h2, sig2, ksi_2, tau2_2, ksi_1, tau2_1, rho, Z, X, int_gs1 = TRUE, int_gs2 = TRUE, int_s1s2 = FALSE, int_gs1s2 = FALSE, nDivisions = 5L, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_calc_OMEGA_twosim`, Y, G, S1, R1, S2, R2, lowerS1, upperS1, lowerS2, upperS2, beta, gamma_1, gamma_2, psi_1, psi_2, h1, h2, sig2, ksi_2, tau2_2, ksi_1, tau2_1, rho, Z, X, int_gs1, int_gs2, int_s1s2, int_gs1s2, nDivisions, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

deltaCI_twosim <- function(mu1, sig1, mu2, sig2, sig12, indL = 1, mu3 = 0L, sig3 = 0L, sig13 = 0L, sig23 = 0L, alpha = 0.05) {
    .Call(`_mmed_deltaCI_twosim`, mu1, sig1, mu2, sig2, sig12, indL, mu3, sig3, sig13, sig23, alpha)
}

bootstrapCI_twosim <- function(y, g, s1, r1, s2, r2, Z, X, lowers1, uppers1, lowers2, uppers2, delta1, delta2, alpha, int_gs1 = TRUE, int_gs2 = TRUE, int_s1s2 = FALSE, int_gs1s2 = FALSE, indL = 1, bootStrapN = 1000L, convLimit = 1e-4, iterationLimit = 1e4, nDivisions = 5L, MEASURE_TYPE_KNOWN = 1L, MEASURE_TYPE_MISSING = 0L, MEASURE_TYPE_BELOW_DETECTION_LIMIT = -1L, MEASURE_TYPE_ABOVE_DETECTION_LIMIT = 2L) {
    .Call(`_mmed_bootstrapCI_twosim`, y, g, s1, r1, s2, r2, Z, X, lowers1, uppers1, lowers2, uppers2, delta1, delta2, alpha, int_gs1, int_gs2, int_s1s2, int_gs1s2, indL, bootStrapN, convLimit, iterationLimit, nDivisions, MEASURE_TYPE_KNOWN, MEASURE_TYPE_MISSING, MEASURE_TYPE_BELOW_DETECTION_LIMIT, MEASURE_TYPE_ABOVE_DETECTION_LIMIT)
}

mcCI_twosim <- function(mu, sig, delta, indL = 1.0, nIt = 10000, alpha = 0.05) {
    .Call(`_mmed_mcCI_twosim`, mu, sig, delta, indL, nIt, alpha)
}

